#!/bin/bash

__devkit_logo() {
  printf "\n"
  printf "\e[90m  ██████╗ ███████╗██╗   ██╗██╗  ██╗██╗████████╗\e[0m\n"
  printf "\e[90m  ██╔══██╗██╔════╝██║   ██║██║ ██╔╝██║╚══██╔══╝\e[0m\n"
  printf "\e[90m  ██║  ██║█████╗  ██║   ██║█████╔╝ ██║   ██║\e[0m\n"
  printf "\e[90m  ██║  ██║██╔══╝  ╚██╗ ██╔╝██╔═██╗ ██║   ██║\e[0m\n"
  printf "\e[90m  ██████╔╝███████╗ ╚████╔╝ ██║  ██╗██║   ██║\e[0m\n"
  printf "\e[90m  ╚═════╝ ╚══════╝  ╚═══╝  ╚═╝  ╚═╝╚═╝   ╚═╝\e[0m\n"
  printf "\n"

  sleep 0.5

  if [ -z "$TAG_VERSION" ]; then
    printf "\e[97m\e[1m  Version: \e[0m\e[93m(running on local)\e[0m\n"
  else
    printf "\e[97m\e[1m  Version: \e[0m\e[90m%s\e[0m\n" "$TAG_VERSION"
  fi

  printf "\n"

  sleep 1
}

__devkit_logo

__DEVKIT_CMD_NOT_AVAILABLE=()

__DEVKIT_CMD_OPTIONAL=()

__devkit_command_exists() {
  local optional=false

  if [ "$1" == "--optional" ]; then
    optional=true
    shift
  fi

  if command -v "$1" &>/dev/null; then
    printf "\e[90m  [\e[32m ✔ \e[90m] \e[97m\e[1m%s\e[0m is available\e[0m\n" "$1"
    sleep 0.1
  else
    if [ "$optional" == true ]; then
      printf "\e[90m  [\e[33m • \e[90m] \e[97m\e[1m%s\e[0m is not available \e[90m(optional)\e[0m\n" "$1"
      __DEVKIT_CMD_OPTIONAL+=("$1")
    else
      printf "\e[90m  [\e[31m ✖ \e[90m] \e[97m\e[1m%s\e[0m is not available\e[0m\n" "$1"
      __DEVKIT_CMD_NOT_AVAILABLE+=("$1")
    fi
    sleep 0.1
  fi
}

__devkit_report_not_available() {
  if [ ${#__DEVKIT_CMD_NOT_AVAILABLE[@]} -gt 0 ]; then
    printf "\n\e[90m  [\e[31m✖\e[90m] \e[97m\e[1mThe following commands are not available:\e[0m\n"
    for cmd in "${__DEVKIT_CMD_NOT_AVAILABLE[@]}"; do
      printf "\e[90m    - \e[97m\e[1m%s\e[0m\n" "$cmd"
    done

    printf "\n\e[90m  [\e[33m•\e[90m] \e[97m\e[1mPlease install the required packages or ensure the commands are available in your \e[34mPATH\e[97m\e[1m and try again...\e[0m\n"
    exit 1
  fi
}

__devkit_command_exists "git"
__devkit_command_exists "pwsh"
__devkit_command_exists "curl"
__devkit_command_exists --optional "wget"
__devkit_command_exists "ssh"

__devkit_report_not_available
