import = [ "~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml", "~/.config/alacritty/font-size.toml", "~/.local/share/devkit/defaults/alacritty.toml" ]

[window]
padding.x = 30
padding.y = 30
